[uwsgi]
http = :8081
module = websocket
callable = application
gevent = 100
gevent-monkey-patch = true
master = true
processes = 4
vacuum = true
lazy-apps = true
max-requests = 1000
stats = :1717

# Optional: enable buffering and thread pool if needed
# buffer-size = 32768
# threads = 2
